version: "3.7"
services:
  wazuh-manager:
    image: wazuh/wazuh:latest
    hostname: wazuh-manager
    container_name: wazuh-manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    restart: always

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:latest
    hostname: wazuh-dashboard
    container_name: wazuh-dashboard
    links:
      - wazuh-manager
    depends_on:
      - wazuh-manager
    environment:
      - WAZUH_MANAGER=wazuh-manager
    ports:
      - "443:443"
    restart: always

